# Generated by Django 5.1.1 on 2024-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryAPI', '0002_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='libraryAPI.author'),
        ),
    ]
